# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hamp
email: hamedmp2012 [at] gmail
description: >
  AI, Data Science and some Futiristic stuff
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hamedmp.github.io" # the base hostname & protocol for your site
paginate: 10 # The number of posts to show per page on your homepage

name: 'Hamed MP'
bio: >
  Deep learning, Big data and a cup of coffee.
author_image: "/assets/images/author.png"
twitter_username: thehamedmp
github_username:  hamedmp

# Google Analytics
analytics_id: "UA-70042280-1"

# tags url
# permalink: /:tags/:title/

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-time-to-read
