# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Hamed MP
tagline:          'Machine Learnin, Data Science, and a cup of Coffee..'
description:      'Machine Learnin, Data Science, and a cup of Coffee..'
url:              http://hamedmp.github.io
baseurl:          /
gems:				 			[jekyll-paginate, jekyll-gist]
author:
  name:           'Hamed MP'
  url:            https://twitter.com/hamedpc2002

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
